language: node_js
node_js:
  - "8.11.2"
dist: trusty #needs Ubuntu Trusty
sudo: required
addons:
  chrome: stable #installing Chrome on Travis to run tests
cache:
  directories:
    — node_modules
before_install:
  - mysql -e "CREATE DATABASE pcprepkit; CREATE USER 'pcprepkit' IDENTIFIED BY 'pcprepkit'; GRANT ALL PRIVILEGES ON pcprepkit.* TO 'pcprepkit' WITH GRANT OPTION"
install:
  - npm install
  - npm build
before_script:
  - npm start &
  - sleep 60
script:
  - ./node_modules/.bin/mocha --timeout 10000
  - ng test --watch=false
